const mongoose = require('mongoose');

const chatSchema = new mongoose.Schema({
    from:{
        type: String,
        require:true

    },
    to:{
        type: String,
        require :true
    },
    msg:{
        type: String,
        maxLength:90 // add the constrain
    },
    created_at:{
        type:String,
        require:true
    },
    id: {
        type: Number //ok then 
        // that's it then normally you will use this id now but remember one thing 
        // you can't use the methods like Chat.findById(id)
        // becuse you are passing your id but it requires the mongodb id which is generated by mongodb itself
        // that hepped without install uuid
        // no after uuid also same will come I think so.. because mongodb will search using it's own id
        // so insted you can use like this Chat.find({id: id})
        // like this.. without uuid right?
        // yes without only
        // and with uuid simple defined  as above right yess
    }

}) ;
//create model collection nmae that in mogoosh will be  Chats
const Chat = mongoose.model("chats",chatSchema);

module.exports = Chat;


// okkk?
// json extension u install  what they do
// ill show the json data in a proper format like adding spaces  etc..
